using System.Text;
using System.Text.Json;
using PhaseA.Platform.Data;

namespace PhaseA.Platform.Runs;

public sealed class PrototypeRouteStateWriter
{
    private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true
    };

    public void WriteProjectReadme(ProjectSnapshot project)
    {
        ArgumentNullException.ThrowIfNull(project);

        Directory.CreateDirectory(project.RepoPath);
        var path = Path.Combine(project.RepoPath, "README.md");
        File.WriteAllText(path, BuildProjectReadme(project), Utf8NoBom);
    }

    public void WriteProjectReadme(
        string repoPath,
        string projectId,
        string accountId,
        string projectName,
        string gameName,
        string gameTypeSource,
        string templateRuleId,
        string workspaceId,
        string metaPath)
    {
        Directory.CreateDirectory(repoPath);
        var path = Path.Combine(repoPath, "README.md");
        File.WriteAllText(
            path,
            BuildProjectReadme(projectId, accountId, projectName, gameName, gameTypeSource, templateRuleId, workspaceId, metaPath),
            Utf8NoBom);
    }

    public void WritePrototypeState(ProjectSnapshot project, object payload)
    {
        WriteState(project, Path.Combine("routes", "prototype", "latest.json"), payload);
    }

    public void WriteIterationPlanState(ProjectSnapshot project, object payload)
    {
        WriteState(project, Path.Combine("routes", "iteration-plan", "latest.json"), payload);
    }

    public void WriteNeedsFixState(ProjectSnapshot project, int goalIndex, object payload)
    {
        var step = goalIndex <= 0 ? "step-unknown" : $"step-{goalIndex:00}";
        WriteState(project, Path.Combine("routes", "needs-fix", step, "latest.json"), payload);
    }

    public string ReadProjectReadme(ProjectSnapshot project)
    {
        var path = Path.Combine(project.RepoPath, "README.md");
        return File.Exists(path) ? File.ReadAllText(path, Encoding.UTF8) : "";
    }

    public string ReadLatestNeedsFixState(ProjectSnapshot project, int goalIndex)
    {
        var step = goalIndex <= 0 ? "step-unknown" : $"step-{goalIndex:00}";
        return ReadState(project, Path.Combine("routes", "needs-fix", step, "latest.json"));
    }

    public string ReadLatestPrototypeState(ProjectSnapshot project)
    {
        return ReadState(project, Path.Combine("routes", "prototype", "latest.json"));
    }

    private static void WriteState(ProjectSnapshot project, string relativePath, object payload)
    {
        var path = Path.Combine(project.MetaPath, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, JsonSerializer.Serialize(payload, JsonOptions), Utf8NoBom);
    }

    private static string ReadState(ProjectSnapshot project, string relativePath)
    {
        var path = Path.Combine(project.MetaPath, relativePath);
        return File.Exists(path) ? File.ReadAllText(path, Encoding.UTF8) : "";
    }

    private static string BuildProjectReadme(ProjectSnapshot project)
    {
        return BuildProjectReadme(
            project.ProjectId,
            project.AccountId,
            project.Name,
            project.GameName,
            project.GameTypeSource,
            project.TemplateRuleId,
            project.WorkspaceId,
            project.MetaPath);
    }

    private static string BuildProjectReadme(
        string projectId,
        string accountId,
        string projectName,
        string gameName,
        string gameTypeSource,
        string templateRuleId,
        string workspaceId,
        string metaPath)
    {
        return $"""
            # {projectName}

            This file is generated by Phase A for project-level recovery.

            ## Project

            - ProjectId: {projectId}
            - AccountId: {accountId}
            - WorkspaceId: {workspaceId}
            - ProjectName: {projectName}
            - GameName: {gameName}
            - GameTypeSource: {gameTypeSource}
            - TemplateRuleId: {templateRuleId}

            ## Prototype Route Contract

            - Prototype route state: meta/routes/prototype/latest.json
            - Iteration plan route state: meta/routes/iteration-plan/latest.json
            - Needs fix route state: meta/routes/needs-fix/step-XX/latest.json

            ## Recovery Rules

            - Start from this README to identify the project and game type.
            - For needs fix, read only the current step state under meta/routes/needs-fix/step-XX.
            - If the current step has no needs fix state, read meta/routes/prototype/latest.json.
            - Do not consume other steps' needs fix state.
            - Project meta root: {metaPath}
            """;
    }
}
